name: C++ CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: sudo apt-get install -y libeigen3-dev cmake 
    - name: configure
      run: cd cpp && mkdir build && cd build && cmake -DTESTPSFLIB=ON ..
    - name: make
      run: cd cpp/build && make
    - name: Run Test
      run: cd cpp/build && ./runPsfLibTests
