name: C++ CI

on:
  push:
    branches: [ cpp ]

  pull_request:
    branches: [ cpp ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install gtest manually
      run: sudo apt-get install -y libgtest-dev libeigen3-dev cmake && sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz && sudo tar xf release-1.7.0.tar.gz && cd googletest-release-1.7.0 && sudo cmake -DBUILD_SHARED_LIBS=ON . && sudo make && sudo cp -a include/gtest /usr/include
    - name: configure
      run: cd cpp && mkdir build && cd build && cmake -DTESTPSFLIB=ON ..
    - name: make
      run: cd cpp/build && make
    - name: Run Test
      run: cd cpp/build && ./runPsfLibTests